### ISSUE TITLE
hello,what's wrong?

### ISSUE THREAD

**Issue by AnserBaby** [Bukk94/CoubDownloader#4]
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at CoubDownloader.Crawler.DownloadJson(String url, String token)
   at CoubDownloader.Crawler.GetLinks(String baseUrl, Int32 page, String token, Nullable`1 totalPagesToDownload)
   at CoubDownloader.Crawler.DownloadLinks(String baseUrl, String dir, String token, Nullable`1 totalPages)
   at CoubDownloader.Crawler.DownloadChannelCoubs(String channel)
   at CoubDownloader.Crawler.CrawlUrls(String[] categories)
   at CoubDownloader.Program.GetCoubs(String input, Configuration configuration)
   at CoubDownloader.Program.Main()

**Comment by Bukk94** [comment]
@AnserBaby Hi, it seems that coub you want to download is not available and Coub websites returns 404 (not found). Are you downloading all coubs from channel/liked/bookmarked or you are supplying your own list of URLs?
One of them was most likely deleted. Removing it from the list will fix the problem.

And I should probably implement some sort of handling to skip non-existing coubs :)

**Comment by Bukk94** [comment]
Hi @AnserBaby, back to your problem.
The downloader failed, because you tried to download channel that doesn't exist. You have to enter channel's username (found in the URL), not display name. This cause the crash.

But I fixed this and it won't happen again. If you enter invalid channel name, it will tell you and it will skip it (meaning it won't crash).
You can download the changes in newest v0.10 version: https://github.com/Bukk94/CoubDownloader/releases/tag/v0.10
