### ISSUE TITLE
Full version wouldn't oblige.

### ISSUE THREAD

**Issue by ghost** [Bukk94/CoubDownloader#6]
Input: blvk3sp@c3
System.Net.WebException: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at CoubDownloader.Crawler.VerifyIfChannelExists(String channel)
   at CoubDownloader.Crawler.DownloadChannelCoubs(String channel)
   at CoubDownloader.Crawler.CrawlUrls(String[] categories)
   at CoubDownloader.Program.GetCoubs(String input, Configuration configuration)
   at CoubDownloader.Program.Main()
   
   (+What is the command to add the token?)

**Comment by Bukk94** [comment]
Hi, can you provide your input? What have you tried to download?

**Comment by Bukk94** [comment]
@TadyHUN I tried your input. It seems that you are using your Display name instead of username. To download your channel/profile, you need to use your username. This username can be found when you open your profile and you'll look in the URL. 
It is something like `https://coub.com/username1234`. So add just `username1234` to the program input. As for the token, you'll be asked by the application to insert it when it needs it.

**Comment by ghost** [comment]
Thx!
